version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PRIMARY_USER: "${POSTGRES_PRIMARY_USER}"
      POSTGRES_PRIMARY_PASSWORD: "${POSTGRES_PRIMARY_PASSWORD}"
      POSTGRES_ROOT_PASSWORD: "${POSTGRES_ROOT_PASSWORD}"
      POSTGRES_DATABASE: "${POSTGRES_DATABASE}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_PASSWORD}"
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - postgres
    restart: always

volumes:
  postgres:

networks:
  postgres:
    driver: bridge
